### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by aidan-mueller** [cobelu/Long-EZ#1]
I would be interested in contributing to this project. I've looked at the markdown files and I have found things I could work on.

Before I proceed, I would like to know if @cobelu has any uncommitted changes, and I would also like to know about the status of this project and whether it is still alive.

**Comment by cobelu** [comment]
Hi Aidan,

The status is still alive. I am in grad school and try to work on it during breaks. Due to COVID, everything went online, and my screen time has been off the charts lately, so I haven’t been working on it lately. I have no uncommitted changes.

It’s super boring work, but if you’d like to contribute, please help! The materials list is definitely one of the immediate things that I can think of, but the TODO should be pretty up to date still and helpful. 

Best,
Connor
